//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

using Microsoft.Scripting.Hosting;
using IronPython.Hosting;
using System.IO;


public struct PythonCommand
{
	public string CommandName;
	public string Description;
	public int AccessLevel;
	public Action<FriendContainer, string[]> Function;
}

public class PythonFile
{
    public ResponseHandler ParentHandler;
    public static ScriptEngine Engine;
    public ScriptScope Scope;
    public ScriptSource Source;

	public PythonFile()
	{
        Scope = Engine.CreateScope();
    }

    public void LoadFile(string path)
    {
        Source = Engine.CreateScriptSourceFromFile(path);
		Console.WriteLine("Loading: "+path);
		try
		{
			Source.Compile();
			Source.Execute(Scope);
		}
		catch(Exception e)
		{
			Console.WriteLine(e.ToString());
		}
    }

	public void ExecutePrecache()
    {
		if(Scope.ContainsVariable("OnLoaded"))
		{
			Action<PythonFile> Function = Scope.GetVariable<Action<PythonFile>>("OnLoaded");
			Function(this);
		}
	}

	public void AddCommand(string name, string functionname, int accesslevel, string description)
	{
		Action<FriendContainer, string[]> function = Scope.GetVariable<Action<FriendContainer, string[]>>(functionname);
		PythonCommand command = new PythonCommand();
		command.CommandName = name;
		command.AccessLevel = accesslevel;
		command.Description = description;
		command.Function = function;
		ParentHandler.PythonCommands.AddFirst(command);
	}
}
